### ISSUE TITLE
ball getting stuck

### ISSUE THREAD

**Issue by SingleSlice** [ThatCookie/PBR#7]
**Describe the bug**
the ball gets stuck in the paddle when going too fast and hits the right side of the wall (may not do it all the times)
**To Reproduce**
1)make the ball bounce on the paddle
2)hits the right side of the wall
3)hits the paddle again and gets stuck

**Expected behavior**
should not get stuck and bounce off the paddle instead

**Comment by ThatCookie** [comment]
With the new collision algorithm, this should be fixed.
